services:
  db:
    image: postgres:18
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

volumes:
  postgres_data: